---
kind: Service
apiVersion: v1
metadata:
  name: demo01-web-svc
  labels:
    app: web
    env: sc
  namespace: sc-ns-01
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-httpd

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo01-centos7-httpd
  labels:
    app: web
    env: sc
  namespace: sc-ns-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-httpd
  template:
    metadata:
      labels:
        app: demo-httpd
    spec:
      containers:
      - name: httpd
        image: gowatana/centos7:httpd
        ports:
        - containerPort: 80
          protocol: TCP
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - demo-httpd
            topologyKey: "kubernetes.io/hostname"

